development:
  adapter: postgresql
  encoding: unicode
  database: solo_development
  pool: 5
  username: admin
  password:
  host: localhost




test:
  adapter: postgresql
  encoding: unicode
  database: solo_test
  pool: 5
  username: admin
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: solo_production
  pool: 5
  username: admin
  password:
  host: localhost
